version: 2.1

# List of all jobs.
jobs:
  # Build and test the project.
  build-and-test:
    docker:
      - image: circleci/postgres:10.9
    steps:
      # Update the project.
      - checkout

      # Install Rust.
      - run:
          name: Install Rust
          command: |
              test -d /usr/local/cargo || curl https://sh.rustup.rs -sSf | sh -s -- -y

      # Install `just` used to manage the project.
      - run:
          name: Install just
          command: |
              export PATH="$HOME/.cargo/bin:$PATH"
              test -f $HOME/.cargo/bin/just || cargo install just

      # Build the extension.
      - run:
          name: Build the extension
          command: |
              export PATH="$HOME/.cargo/bin:$PATH"
              just build

      # Initialize a Postgres database.
      - run:
          name: Set up Postgres
          command: |
              export PATH="$HOME/.cargo/bin:$PATH"
              just pg-init

      # Run the extension test suites.
      - run:
          name: Test the extension
          command: |
              export PATH="$HOME/.cargo/bin:$PATH"
              just pg-start
              just test


# List of workflows.
workflows:
  version: 2

  # The build workflow.
  build:
    jobs:
      # Run the `build-and-test` job for the `trying` and `staging` branches and all tags.
      - build-and-test:
          filters:
            branches:
              only:
                - trying
                - staging
            tags:
              only: /.*/
